/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Collection: typeof import('./src/components/Collection.vue')['default']
    CollectionDetail: typeof import('./src/components/CollectionDetail.vue')['default']
    CollectionGroups: typeof import('./src/components/CollectionGroups.vue')['default']
    CollectionPreview: typeof import('./src/components/CollectionPreview.vue')['default']
    Collections: typeof import('./src/components/Collections.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconPanel: typeof import('./src/components/IconPanel.vue')['default']
    Icons: typeof import('./src/components/Icons.vue')['default']
    Result: typeof import('./src/components/Result.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
  }
}
